#!/bin/bash
# FreeFalcon 6 — Linux Port: end-user install script.
#
# Installs the locally-built FFViper engine against a user-supplied FreeFalcon/
# Falcon data installation (the game data is NOT redistributable, so the user
# brings their own — e.g. from an existing Windows/Wine install).
#
# Usage:
#   packaging/install.sh --data /path/to/FreeFalcon6 [--prefix ~/.local]
#
# What it does:
#   1. Verifies the engine is built and the data dir looks like a FreeFalcon install.
#   2. Ensures the `sim -> Zips/sim` symlink the Linux resource path needs.
#   3. Checks runtime shared-library dependencies and reports any that are missing.
#   4. Installs a launcher (`freefalcon`) and a .desktop entry into the prefix.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="$REPO/build/src/ffviper/FFViper"
DATA=""
PREFIX="$HOME/.local"

while [ $# -gt 0 ]; do
  case "$1" in
    --data)   DATA="$2"; shift 2 ;;
    --prefix) PREFIX="$2"; shift 2 ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

err() { echo "ERROR: $*" >&2; exit 1; }

# --- 1. preflight ----------------------------------------------------------
[ -x "$BIN" ] || err "engine not built: $BIN  (run: cd $REPO/build && ninja)"
[ -n "$DATA" ] || err "pass --data /path/to/FreeFalcon6 (your game-data install)"
DATA="$(cd "$DATA" 2>/dev/null && pwd)" || err "data dir not found"
# A FreeFalcon data tree has terrdata/ and at least one of the known launchers/dirs.
[ -d "$DATA/terrdata" ] || err "'$DATA' has no terrdata/ — not a FreeFalcon data dir?"

echo ">> engine: $BIN"
echo ">> data:   $DATA"
echo ">> prefix: $PREFIX"

# --- 2. sim symlink (Linux resource path bypasses zip mounting) ------------
if [ ! -e "$DATA/sim" ]; then
  if [ -d "$DATA/Zips/sim" ]; then
    ln -s "Zips/sim" "$DATA/sim"
    echo ">> created sim -> Zips/sim symlink"
  else
    echo "!! WARNING: no '$DATA/sim' and no Zips/sim to link it to."
    echo "   If resources fail to load, locate the extracted sim/ tree and symlink it."
  fi
fi

# --- 3. runtime dependency check -------------------------------------------
echo ">> checking runtime libraries..."
MISSING="$(ldd "$BIN" 2>/dev/null | awk '/not found/{print $1}')"
if [ -n "$MISSING" ]; then
  echo "!! Missing shared libraries:"
  echo "$MISSING" | sed 's/^/     /'
  echo "   On Debian/Ubuntu try: sudo apt-get install libsdl2-2.0-0 libglew2.2 libopenal1 libgl1"
  echo "   (GLEW is also bundled in $REPO/extern; the binary's RUNPATH points there.)"
else
  echo ">> all shared libraries resolve."
fi

# --- 4. launcher + desktop entry -------------------------------------------
mkdir -p "$PREFIX/bin" "$PREFIX/share/applications"
LAUNCHER="$PREFIX/bin/freefalcon"
cat > "$LAUNCHER" <<EOF
#!/bin/bash
# Generated by packaging/install.sh
cd "$DATA" || exit 1
exec "$BIN" -d "$DATA" -w "\$@"
EOF
chmod +x "$LAUNCHER"
echo ">> installed launcher: $LAUNCHER"

cat > "$PREFIX/share/applications/freefalcon.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=FreeFalcon 6 (Linux Port)
Comment=Falcon 4.0 lineage F-16 combat flight simulator
Exec=$LAUNCHER
Terminal=false
Categories=Game;Simulation;
EOF
echo ">> installed desktop entry"

echo
echo "Done. Run with:  $LAUNCHER         (ensure $PREFIX/bin is on your PATH)"
echo "             or:  $LAUNCHER -test-ia   (jump straight into Instant Action)"
