#!/usr/bin/env python3
"""FF-KEYMAP-1: generate the FreeFalcon keyboard map from the key file the game loads.

The game loads config/<PlayerOptions keyfile>.key (Viper.pop -> "keystrokes"), falling back to
config/keystrokes.key (src/sim/siminput/setupinp.cpp LoadFunctionTables). Line format, per the
sscanf there: func buttonId mouseSide key mod prefixKey prefixMod flags "description".
key/prefixKey are DirectInput scancodes; mod bits SHIFT 1, CTRL 2, ALT 4. prefixKey != 0 makes a
two-key chord (press prefix, then key). key -1 = not loaded; key -2 = joystick button buttonId; prefix -1 = menu (digits after the key).
Usage: ff_keymap.py <keyfile> [src/sim/siminput/findfunc.cpp] > KEYMAP.md
With findfunc.cpp, bindings whose callback the program lacks are marked dead (FindFunctionFromString
returns NULL and the line is dropped), and program commands with no default key are listed.
"""
import re, sys, collections

DIK = {0x01:'Esc',0x02:'1',0x03:'2',0x04:'3',0x05:'4',0x06:'5',0x07:'6',0x08:'7',0x09:'8',0x0A:'9',
0x0B:'0',0x0C:'-',0x0D:'=',0x0E:'Backspace',0x0F:'Tab',0x10:'Q',0x11:'W',0x12:'E',0x13:'R',0x14:'T',
0x15:'Y',0x16:'U',0x17:'I',0x18:'O',0x19:'P',0x1A:'[',0x1B:']',0x1C:'Enter',0x1D:'LCtrl',0x1E:'A',
0x1F:'S',0x20:'D',0x21:'F',0x22:'G',0x23:'H',0x24:'J',0x25:'K',0x26:'L',0x27:';',0x28:"'",0x29:'`',
0x2A:'LShift',0x2B:'\\',0x2C:'Z',0x2D:'X',0x2E:'C',0x2F:'V',0x30:'B',0x31:'N',0x32:'M',0x33:',',
0x34:'.',0x35:'/',0x36:'RShift',0x37:'Num*',0x38:'LAlt',0x39:'Space',0x3A:'CapsLock',0x3B:'F1',
0x3C:'F2',0x3D:'F3',0x3E:'F4',0x3F:'F5',0x40:'F6',0x41:'F7',0x42:'F8',0x43:'F9',0x44:'F10',
0x45:'NumLock',0x46:'ScrollLock',0x47:'Num7',0x48:'Num8',0x49:'Num9',0x4A:'Num-',0x4B:'Num4',
0x4C:'Num5',0x4D:'Num6',0x4E:'Num+',0x4F:'Num1',0x50:'Num2',0x51:'Num3',0x52:'Num0',0x53:'Num.',
0x57:'F11',0x58:'F12',0x9C:'NumEnter',0x9D:'RCtrl',0xB5:'Num/',0xB7:'PrintScreen',0xB8:'RAlt',
0xC5:'Pause',0xC7:'Home',0xC8:'Up',0xC9:'PgUp',0xCB:'Left',0xCD:'Right',0xCF:'End',0xD0:'Down',
0xD1:'PgDn',0xD2:'Insert',0xD3:'Delete',0xDB:'LWin',0xDC:'RWin',0xDD:'Apps'}

def mods(m):
    return ''.join(n + '+' for b, n in ((2, 'Ctrl'), (4, 'Alt'), (1, 'Shift')) if m & b)

def keyname(k, m):
    return mods(m) + DIK.get(k, '0x%02X' % k)

LINE = re.compile(r'^(\S+)\s+(-?\d+)\s+(-?\d+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(-?\d+)\s+"([^"]*)"')
JOY = re.compile(r'^(\S+)\s+(\d+)\s+(-?\d+)\s+-2\s+0\s+0x0\s+0$')
GROUP = {'Ckpit': 'Cockpit', 'Ctrls': 'Controls', 'Wpn': 'Weapons', 'Sim': 'Simulation', 'Flap': 'Flaps', 'RadiO': 'Radio',
         'Key': 'Other', 'Set': 'Other', 'Toggle': 'Other', 'Cycle': 'Other'}
rows, skipped, joy = [], [], []
for raw in open(sys.argv[1], encoding='latin-1'):
    ln = raw.strip()
    if not ln or ln.startswith(('#', ';', '//')):
        continue
    m = LINE.match(ln)
    j = JOY.match(ln)
    if not m and j:
        joy.append((int(j.group(2)) + 1, j.group(1))); continue
    if not m:
        skipped.append(ln); continue
    func, btn, side, key, mod, pkey, pmod, flags, desc = m.groups()
    key, mod, pkey, pmod = (int(x, 16) for x in (key, mod, pkey, pmod))
    if key == 0xFFFFFFFF:
        binding = '— (not loaded)'
    else:
        binding = keyname(key, mod)
        if pkey == 0xFFFFFFFF:
            # setupinp.cpp: prefix -1 binds 1..0, Esc and SysRq as the SECOND key after this one
            binding = binding + ', then 1–0 / Esc'
        elif pkey != 0:
            binding = keyname(pkey, pmod) + ', then ' + binding
    ctx = 'radio menu' if int(flags) == -2 else ''
    g = re.match(r'([^ -]+)[ -]+(.*)', desc)
    grp, text = (g.group(1), g.group(2)) if g else ('Other', desc)
    rows.append((GROUP.get(grp, grp), text.strip(), binding, func, ctx))

known = None
if len(sys.argv) > 2:
    known = set()
    for ln in open(sys.argv[2], encoding='latin-1'):
        if not ln.lstrip().startswith('//'):
            known.update(re.findall(r'USER_FUNCTION\(\s*(\w+)', ln))
    rows = [(g, t + ('' if f in known else ' **(dead: callback not in program)**'), b, f, c) for g, t, b, f, c in rows]
groups = collections.OrderedDict()
for r in rows:
    groups.setdefault(r[0], []).append(r)
print('# FreeFalcon keyboard map\n')
print('Generated by `tools/ff_keymap.py` from `%s` (the file the game loads; see the script header).' % sys.argv[1].split('/')[-1])
print('%d bindings, %d groups. Program data, not documentation: where a manual disagrees, this wins.\n' % (len(rows), len(groups)))
print('**Linux port keys handled before the key file** (`src/ffviper/main_linux.cpp`): F11 fullscreen;')
print('F5 in the UI quick-launches Instant Action; in the sim, Shift+Num8/4/6/2 select the front/left/right/down')
print('2-D cockpit panel **and are still passed to the sim**, where the key file binds them to DMS up/left/right/down,')
print('so a keyboard DMS press also flips the 2-D panel (backlog FF-KEYPANEL-1). Esc never quits the app.\n')
for g, rs in groups.items():
    print('## %s\n' % g)
    print('| Key | Command | Callback |' + (' Context |' if any(r[4] for r in rs) else ''))
    print('|---|---|---|' + ('---|' if any(r[4] for r in rs) else ''))
    for _, text, b, f, ctx in rs:
        print('| %s | %s | `%s` |%s' % (b.replace('|', '\\|'), text.replace('|', '\\|'), f, (' %s |' % ctx) if any(r[4] for r in rs) else ''))
    print()
if joy:
    print('## Joystick buttons\n')
    print('| Button | Callback |\n|---|---|')
    for n, f in joy: print('| %d | `%s` |' % (n, f))
    print()
if known:
    bound = {r[3] for r in rows} | {f for _, f in joy}
    spare = sorted(known - bound)
    print('## Program commands with no default key (%d)\n' % len(spare))
    print('Bindable from Setup → Controls; names from `UserFunctionList` in findfunc.cpp.\n')
    print(', '.join('`%s`' % f for f in spare) + '\n')
if skipped:
    print('## Unparsed lines (%d)\n' % len(skipped))
    for s in skipped: print('    ' + s)
